paths:
  /api/products/mockingproducts:
    get:
      summary: List 100 test products with the same MongoDB format (you need to be an admin)
      tags:
        - Products
      responses:
        '200':
          description: Products were returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/MockingProduct'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/products:
    get:
      summary: Get all products (you need to be an admin)
      tags:
        - Products
      responses:
        '200':
          description: Products were returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/AllProducts'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new product (you need to be an admin or premium user)
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/BodyCreateProduct'
      responses:
        '201':
          description: The product was created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/CreateProduct'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /api/products/{pid}:
    get:
      summary: Get a product by id (you need to be an admin)
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id of the product being searched
          schema:
            $type: String
      responses:
        '200':
          description: Product found correctly
          content:
            application/json:
              schema:
                $ref: '#components/schemas/ProductById'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update a product by id (The admin user can modify any product, even if it belongs to another user. The premium user can only modify the products that belong to him)
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to update
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/BodyUpdateProduct'
      responses:
        '200':
          description: Product was updated successfully
          content:
            application/json:
              schema:
                $ref: '#components/schemas/UpdateProduct'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete a product by id (The admin user can delete any product, even if it belongs to another user. The premium user can only delete the products that belong to him)
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to delete
          schema:
            $type: String
      responses:
        '200':
          description: Product was deleted successfully
          content:
            application/json:
              schema:
                $ref: '#components/schemas/DeleteProduct'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
      example: { code: 500, name: 'Internal Server Error', cause: 'Something unexpected happened...', message: 'Error server. Usually generating the query or the connection to the DB fails' }
    AllProducts:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated for MongoDB
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        status:
          type: Boolean
          description: Product status (if is it false is an inactive product)
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
            description: Image links
        owner:
          type: String
          description: Product owner, it can be admin or a user email
      example:
        status: success
        msg: Products list
        payload:
          - _id: 6508cc7156a024d698a8db17
            title: Inteligente Acero Salchichas
            description: The Football Is Good For Training And Recreational Purposes
            code: pi5tkvspcl
            price: 1159
            status: true
            stock: 20
            category: banyan
            thumbnail: ['https://loremflickr.com/640/480']
            owner: adminCoder@coder.com
    ProductById:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated for MongoDB
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        status:
          type: Boolean
          description: Product status (if is it false is an inactive product)
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
            description: Image links
        owner:
          type: String
          description: Product owner, it can be admin or a user email
      example:
        status: success
        msg: Product
        payload:
          _id: 6508cce656a024d698a8db1a
          title: Artesanal Acero Guantes
          description: Andy shoes are designed to keeping in mind durability as well as trends, the most stylish range of shoes & sandals
          code: ht0k7bry4j
          price: 597
          status: true
          stock: 25
          category: picnic
          thumbnail: ['https://loremflickr.com/640/480']
          owner: usuario1@usuario.com
    CreateProduct:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated for MongoDB
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        status:
          type: Boolean
          description: Product status (if is it false is an inactive product)
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
            description: Image links
        owner:
          type: String
          description: Product owner, it can be admin or a user email
      example:
        status: success
        msg: Product created
        payload:
          title: Inteligente Acero Salchichas
          description: he Football Is Good For Training And Recreational Purposes
          code: pi5tkvspcl
          price: 1159
          status: true
          stock: 20
          category: banyan
          thumbnail: ['https://loremflickr.com/640/480']
          owner: adminCoder@coder.com
          _id: 6508cc7156a024d698a8db17
    UpdateProduct:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated for MongoDB
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        status:
          type: Boolean
          description: Product status (if is it false is an inactive product)
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
            description: Image links
        owner:
          type: String
          description: Product owner, it can be admin or a user email
      example:
        status: success
        msg: Product updated
        payload:
          _id: 6508cc7156a024d698a8db17
          title: Inteligente Acero Salchichas
          description: The Football Is Good For Training And Recreational Purposes
          code: pi5tkvspcl
          price: 1159
          status: true
          stock: 20
          category: banyan
          thumbnail: ['https://loremflickr.com/640/480']
          owner: adminCoder@coder.com
    DeleteProduct:
      type: object
      properties:
        status:
          type: string
        msg:
          type: string
        payload:
          type: Boolean
          description: Product removed true, product not removed false
      example:
        status: success
        msg: Product deleted
        payload: true
    MockingProduct:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated for Test
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        status:
          type: Boolean
          description: Product status (if is it false is an inactive product)
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
          description: Image links
        owner:
          type: String
          description: Product owner, it can be admin or a user email
      example:
        status: success
        msg: Test products list
        payload:
          - _id: 7eca6c4f-5cdc-4e1d-9507-50130b79eede
            title: Fantástico Acero Patatas fritas
            description: The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive
            code: xx8c03sfp6
            price: 467.00
            status: false
            stock: 0
            category: housewife
            thumbnail: ['https://loremflickr.com/640/480']
            owner: Gabriel71@hotmail.com
  requestBodies:
    BodyCreateProduct:
      type: object
      properties:
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
            description: Image links
      example:
        title: HONOR Magic5 Lite 6.67
        description: El Honor Magic5 Lite con una pantalla AMOLED de 6.67" FHD+ y una tasa de refresco de 120Hz, te brinda una experiencia visual fluida y vibrante. Además, está potenciado por un procesador Snapdragon 695 de última generación, 8GB+5GB de RAM y 256GB de almacenamiento interno.
        code: abc124
        price: 439
        stock: 18
        category: Celulares
        thumbnail:
          [
            'https://laoferta.com.uy/html-uy/smartphones/honor/magic5-lite-128gb/img/img-principal.jpg',
            'https://d391ci4kxgasl8.cloudfront.net/fit-in/524x480/filters:fill(FFFFFF):quality(90):format(webp)/_img_productos/honor-magic5-lite-128gb-foto-gris3.jpg',
            'https://d391ci4kxgasl8.cloudfront.net/fit-in/524x480/filters:fill(FFFFFF):quality(90):format(webp)/_img_productos/honor-magic5-lite-128gb-foto-gris4.jpg',
          ]
    BodyUpdateProduct:
      type: object
      properties:
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
            description: Image links
      example:
        title: HONOR Magic5 Lite 6.67 5G
        description: Celular con potente procesador y memoria ram
        code: abc126
        price: 500
        stock: 68
        category: Celulares
        thumbnail: ['https://laoferta.com.uy/html-uy/smartphones/honor/magic5-lite-128gb/img/img-principal.jpg']
