paths:
  /api/products/mockingproducts:
    get:
      summary: List 100 test products with the same MongoDB format (you need to be an admin)
      tags:
        - Products
      responses:
        '200':
          description: Products were returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/mockingProduct'
        '500':
          description: Server error. Usually generating the query or the connection to the DB fails
  /api/products:
    get:
      summary: Get all products (you need to be an admin)
      tags:
        - Products
      responses:
        '200':
          description: Products were returned successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Product'
        '500':
          description: Server error. Usually generating the query or the connection to the DB fails
    post:
      summary: Create a new product (you need to be an admin or premium user)
      tags:
        - Products
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/createProduct'
      responses:
        '201':
          description: The product was created successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#components/schemas/Success'
        '500':
          description: Server error. Usually generating the query or the connection to the DB fails
  /api/products/{pid}:
    get:
      summary: Get a product by id (you need to be an admin)
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Id of the product being searched
          schema:
            $type: String
      responses:
        '200':
          description: Product found correctly
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Product'
        '500':
          description: Server error. Usually generating the query or the connection to the DB fails
    put:
      summary: Update a product by id (The admin user can modify any product, even if it belongs to another user. The premium user can only modify the products that belong to him)
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to update
          schema:
            $type: String
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#components/requestBodies/updateProduct'
      responses:
        '200':
          description: Product was updated successfully
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Success'
        '500':
          description: Server error. Usually generating the query or the connection to the DB fails
    delete:
      summary: Delete a product by id (The admin user can delete any product, even if it belongs to another user. The premium user can only delete the products that belong to him)
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: Product id to delete
          schema:
            $type: String
      responses:
        '200':
          description: Product was deleted successfully
          content:
            application/json:
              schema:
                $ref: '#components/schemas/Success'
        '500':
          description: Server error. Usually generating the query or the connection to the DB fails
components:
  schemas:
    Success:
      type: object
      properties:
        status:
          type: String
          description: success or error
        message:
          type: String
          description: Response based on user action
      example:
        status: success
        message: Depending on the user action, product created, product updated or product deleted
    mockingProduct:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated for Test
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        status:
          type: Boolean
          description: Product status (if is it false is an inactive product)
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
          description: Image links
        owner:
          type: String
          description: Product owner, it can be admin or a user email
      example:
        _id: 7eca6c4f-5cdc-4e1d-9507-50130b79eede
        title: Fantástico Acero Patatas fritas
        description: The automobile layout consists of a front-engine design, with transaxle-type transmissions mounted at the rear of the engine and four wheel drive
        code: xx8c03sfp6
        price: 467.00
        status: false
        stock: 0
        category: housewife
        thumbnail: ['https://loremflickr.com/640/480']
        owner: Gabriel71@hotmail.com
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: Id autogenerated by MongoDB
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        status:
          type: Boolean
          description: Product status (if is it false is an inactive product)
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
          description: Image links
        owner:
          type: String
          description: Product owner, it can be admin or a user email
      example:
        _id: 64f9fef6c8406b0d8335f790
        title: SAMSUNG Galaxy A34 5G
        description: No te pierdas de nada de lo que te interesa y además capturá tu alrededor con una excelente calidad con el Samsung Galaxy A34 5G.
        code: abc123
        price: 329
        status: true
        stock: 50
        category: Celulares
        thumbnail:
          [
            'https://d391ci4kxgasl8.cloudfront.net/fit-in/524x480/filters:fill(FFFFFF):quality(90):format(webp)/_img_productos/samsung-galaxy-a34-5g-128gb-foto-lima1.jpg',
            'https://d391ci4kxgasl8.cloudfront.net/fit-in/524x480/filters:fill(FFFFFF):quality(90):format(webp)/_img_productos/samsung-galaxy-a34-5g-128gb-foto-lima6.jpg',
            'https://d391ci4kxgasl8.cloudfront.net/fit-in/524x480/filters:fill(FFFFFF):quality(90):format(webp)/_img_productos/samsung-galaxy-a34-5g-128gb-foto-lima8.jpg',
          ]
        owner: admin
  requestBodies:
    createProduct:
      type: object
      properties:
        title:
          type: String
          description: Product name
        description:
          type: String
          description: Product description
        code:
          type: String
          description: Product code
        price:
          type: Number
          description: Product price
        stock:
          type: Number
          description: Product stock
        category:
          type: String
          description: Product category
        thumbnail:
          type: Array
          items:
            type: String
            description: Image links
      example:
        title: HONOR Magic5 Lite 6.67
        description: El Honor Magic5 Lite con una pantalla AMOLED de 6.67" FHD+ y una tasa de refresco de 120Hz, te brinda una experiencia visual fluida y vibrante. Además, está potenciado por un procesador Snapdragon 695 de última generación, 8GB+5GB de RAM y 256GB de almacenamiento interno.
        code: abc124
        price: 439
        stock: 18
        category: Celulares
        thumbnail:
          [
            'https://laoferta.com.uy/html-uy/smartphones/honor/magic5-lite-128gb/img/img-principal.jpg',
            'https://d391ci4kxgasl8.cloudfront.net/fit-in/524x480/filters:fill(FFFFFF):quality(90):format(webp)/_img_productos/honor-magic5-lite-128gb-foto-gris3.jpg',
            'https://d391ci4kxgasl8.cloudfront.net/fit-in/524x480/filters:fill(FFFFFF):quality(90):format(webp)/_img_productos/honor-magic5-lite-128gb-foto-gris4.jpg',
          ]
    updateProduct:
      type: object
      properties:
        title:
          type: String
          description: Product name
        price:
          type: Number
          description: Product price
        stock:
          type: Number
          description: Product stock
      example:
        title: HONOR Magic5 Lite 6.67 5G
        price: 500
        stock: 100
